view-average-grade | James Chiu
jachiu555/student-grade-table pull request #2
Opened 2020-05-10 20:59 UTC by jachiu555

<img width="1680" alt="SGT view-average-grade SS" src="https://user-images.githubusercontent.com/47793897/81510421-6beb8b00-92c6-11ea-92db-850c7b7921fe.png">

2020-05-11 17:04 UTC, scbowler requested changes
Looking good but a couple small things need fixed, see below comments for details.

2020-05-11 17:04 UTC, scbowler commented on components/app.js
> +      averageGrade = totalGrade / grades.length;
Although this probably ultimately works, this calculation doesn't need to be done on every iteration of the `for` loop. The calculation should only be done once after the `for` loop has completed.

2020-05-11 17:04 UTC, scbowler commented on index.html
> +  <script src="components//page-header.js"></script>
You have an extra forward slash `/` in-between `components` and `page-header.js`

2020-05-12 01:10 UTC, WhiskeyJack96 approved these changes
Great!

2020-05-12 01:11 UTC, merged